services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    depends_on:
      - app
      - db
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      -  "3306:3306"
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
        - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

networks:
  laravel:
